#!/bin/sh
echo "[*] Updating system"
sudo pacman -Syu
echo "[*] Installing git"
sudo pacman -S git
echo "[*] Installing yay"
cd /opt
sudo git clone https://aur.archlinux.org/yay-git.git
sudo chown -R $(whoami):$(whoami) ./yay-git
cd yay-git
makepkg -si
echo "[*] Updating with yay"
yay
echo "[*] Installing other packages"
yay -S wget make gcc dunst libnotify slock zsh zsh-autosuggestions zsh-syntax-highlighting xdg-user-dirs sxhkd mpc mpdscribble xdotool maim xorg-xsetroot xclip ncmpcpp mpd neovim ranger pcmanfm sxiv ibus ibus-mozc texliver-most texlive-lang biber xorg-server xorg-xinit xf86-video-intel mesa xf86-video-amdgpu zathura zathura-djvu zathura-pdf-mupdf iwd man-db man-pages texinfo checkupdates+aur sysstat reflector udisks2 mpv python-pip terminus-font ttf-kochi-substitute siji-git xorg-xev
echo "[*] Enabling systemd services"
sudo systemctl enable --now iwd.service
sudo systemctl enable --now systemd-resolved.service
echo "[*] Installing Python software with pip"
pip install https://github.com/beetbox/beets/tarball/master
sudo pip3 install ueberzug
pip install ranger-fm
echo "[*] Installing vim-plug"
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
echo "[*] Installing zsh prompt"
mkdir -p ~/conf/zsh/prompts
cd ~/conf/zsh/prompts
wget https://raw.githubusercontent.com/keeganjk/purification/master/prompt_purification_setup
echo "[*] Making directories"
mkdir -p ~/doc/git
mkdir -p ~/pic/scsx
mkdir -p ~/misc/bin
mkdir -p ~/misc/run
cd ~/doc/git
echo "[*] Cloning and installing Suckless software"
git clone https://github.com/keeganjk/dwm
git clone https://github.com/keeganjk/st-luke
git clone https://github.com/keeganjk/dmenu
cd dwm; sudo make clean install && cd ..
cd st-luke; sudo make clean install && cd ..
cd dmenu; sudo make clean install && cd ..
echo "[*] Cloning and installing dotfiles with symlink"
git clone https://github.com/keeganjk/dotfiles
ln -s ~/doc/git/dotfiles/home/conf ~/conf
ln -s ~/doc/git/dotfiles/home/.config ~/.config
ln -s ~/doc/git/dotfiles/home/.zshenv ~/.zshenv
echo "[*] Creating Xauthority file"
touch ~/misc/run/Xauthority
cd ~
echo "[*] Changing shell to zsh, setting default user directories"
chsh -s $(which zsh) $(whoami) # Changes default shell to zsh
echo "[*] Now open zsh in order to acknowledge ~/.zshenv" 
#xdg-user-dirs-update # Sets default user directories
