#!/bin/bash

#For keyboard
export GTK_IM_MODULE=xim
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=xim
ibus-daemon -drx --panel /usr/lib/ibus/ibus-ui-gtk3
setxkbmap -option compose:ralt

#For audio
pulseaudio &

# Mount HDD
udisksctl mount -b /dev/sdb1

# Automatically start some services
mpd "$XDG_CONFIG_HOME"/mpd/mpd.conf
mpdscribble

#For GUI 
xrdb -load "$XDG_CONFIG_HOME/X11/xresources"
sleep 1
xsetroot -solid "#101010"
dunst &
sxhkd &
dwmstatus &
exec dwm
